variables:
- name: BuildParameters.solution
  value: '**\*.sln'

name: v$(Major).$(Minor).$(Patch)

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: 4.4
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: $(BuildParameters.solution)
    feedsToUse: 'select'
- task: VSBuild@1
  displayName: 'Build Solution'
  inputs:
    solution: $(BuildParameters.solution)
    configuration: $(BuildConfiguration)
    clean: true
- task: GitHubRelease@1
  displayName: "Publish Relase To GitHub"
  inputs:
    gitHubConnection: 'GitHub PAT'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: '$(Build.BuildNumber)'
    title: '$(Build.BuildNumber) - $(BuildConfiguration) - $(Build.SourceBranchName)'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'