variables:
- name: BuildParameters.solution
  value: '**\*.sln'

name: v$(Major).$(Minor).$(Patch)

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: VSBuild@1
  displayName: 'Build Solution'
  inputs:
    solution: $(BuildParameters.solution)
    configuration: $(BuildConfiguration)
    restoreNugetPackages: true
    clean: true